### ISSUE TITLE
how to build this?

### ISSUE THREAD

**Issue by jason-zou** [Mobile-Artificial-Intelligence/maid#500]
could you please provide the detailed steps of building this app?

**Comment by danemadsen** [comment]
What platform are you on and what are you trying to build for?

For Linux you can just run 
`git clone --recursive https://github.com/Mobile-Artificial-Intelligence/maid.git`
`cd maid`
`source ./setup_flutter.sh`
`flutter build linux`

With windows its very similar except instead of `source ./setup_flutter.sh` you just run `./setup_flutter.bat`
