### ISSUE TITLE
F-Droid can't build

### ISSUE THREAD

**Issue by licaon-kter** [Mobile-Artificial-Intelligence/maid#582]
..as you've removed the custom versionCode code: https://github.com/Mobile-Artificial-Intelligence/maid/compare/1.2.8...main#diff-9526ccfd1d1813ed49c39f8c54dbeb512607376a007d824b905bc8b4e4d202d9L104 and it went back to Flutter defaults

ref: https://gitlab.com/fdroid/fdroiddata/-/jobs/7270851929#L935

/LE: fyi https://gitlab.com/fdroid/fdroiddata/-/commit/99d4dbeeeece4cbfd47828bb6a7a9037fbf29ad0

**Comment by danemadsen** [comment]
I'm looking into it. I removed that because for some reason its broken on the latest versions of flutter which I've which i had to move to.

I had a look at some other flutter open source projects and i cant really see how they've fixed it or they might just be on flutter 3.19 still.

**Comment by danemadsen** [comment]
@licaon-kter Ok ive fixed that error but im going to have to change the way build numbers work because google play wont let me upload 2 app bundles with a version code of 29. So... Im switching to using git index's as the build number so this release will be 16971 and 16972. I hope that works with fdroid because i have no other option

**Comment by licaon-kter** [comment]
If it's bigger than older and if arch number is last, yes :)

**Comment by danemadsen** [comment]
@licaon-kter Ok, Ive republished that for you. While im at it i should probably change the name of the apk's from maid-x86_64.apk and maid-arm64-v8a.apk to maid-android-x86_64.apk and maid-android-arm64-v8a.apk as im releasing more platforms and the release page gets confusing.

Would you like me to open up a PR for you or do you want to handle it yourself?

**Comment by linsui** [comment]
A PR is welcomed. :)

**Comment by licaon-kter** [comment]
reopen pls

ref: https://gitlab.com/fdroid/fdroiddata/-/jobs/7489541666

How does one build these libs: https://github.com/Mobile-Artificial-Intelligence/babylon_tts/tree/496035d9fed365b02d9934bcb531f1394652b358/android/src/main/jniLibs ?

**Comment by licaon-kter** [comment]
disabled autoupdates: https://gitlab.com/fdroid/fdroiddata/-/commit/2313f1249d85ca5faed7beed97eac57657d261d7

**Comment by danemadsen** [comment]
Hi 

> reopen pls
> 
> ref: https://gitlab.com/fdroid/fdroiddata/-/jobs/7489541666
> 
> How does one build these libs: https://github.com/Mobile-Artificial-Intelligence/babylon_tts/tree/496035d9fed365b02d9934bcb531f1394652b358/android/src/main/jniLibs ?
> 
> /LE: fyi https://gitlab.com/fdroid/fdroiddata/-/commit/e295268c3cc3db413021fee50df8d6c2d9f4e9c7

Those libs are build by the CI of babylon.cpp

This is the run which corresponds to the one packaged in that update (1.3.0)
https://github.com/Mobile-Artificial-Intelligence/babylon.cpp/actions/runs/10196582577
commit hash: 58748ffca96ed25f5c2a2fddae325be80fd3ac2e

this is the run that corresponds to the one packaged with 1.3.1
https://github.com/Mobile-Artificial-Intelligence/babylon.cpp/actions/runs/10243168773
commit hash: 99d9d67ba033e1ebe1f2dcb6f1c318cfa22648c9

I had to prebuild them because building them with maid causes errors with the NDK and takes over an hour to complete which constantly times out the CI.

If you want to build them on your own computer you will have to use a specific version of the NDK with CMake version 3.30.1

https://dl.google.com/android/repository/android-ndk-r27-linux.zip

**Comment by licaon-kter** [comment]
F-Droid needs to build them before building the app, yes.

So the recipe needs to be updated to include those build steps.

**Comment by danemadsen** [comment]
@licaon-kter Any chance we can just disable 1.3.0 (since its out of date) and I can get that working for you for 1.3.1?

Im not totally sure how we should do it? I guess we can split the build phases into 3 jobs.

**Comment by licaon-kter** [comment]
1.3.0 is not available, latest is 1.2.9

**Comment by danemadsen** [comment]
@licaon-kter Nevermind ill just roll back the build numbers. Can i keep the binaries for normal builds and then for fdroid builds delete them before rebuilding them in the pipeline?

**Comment by danemadsen** [comment]
@licaon-kter Any examples you know of of a multi-stage pipeline for an fdroid app? Ive almost got the gitlab CI working but im unsure how to integrate it into the fdroid meta

**Comment by danemadsen** [comment]
ok the gitlab ci is passing now, just need some help get the fdroid meta to match it

Im removing the precompiled libs in the ci here

https://github.com/Mobile-Artificial-Intelligence/maid/blob/main/.gitlab/.gitlab-ci.yml#L90

before copying in the libs build by the previous stage
