### ISSUE TITLE
Ollama Error Mobile reload button does nothing

### ISSUE THREAD

**Issue by PrivacyOsint2** [Mobile-Artificial-Intelligence/maid#597]
Error:

After pasting http://10.10.10.2:11434 and hit the reload button nothing happen on home screen. No models show up.

Example URL:
http://10.10.10.2:11434

Using graphine OS Android 14

Screenshot below:
![maid_ollama2](https://github.com/user-attachments/assets/57befa2e-d2ea-41bd-961e-fdbfcc8eda78)

**Comment by danemadsen** [comment]
F-Droid and G Play are both still on the last update. I havnst chnaged anything with ollama since the last update but do me a favor and try out the 1.3.0 release:

https://github.com/Mobile-Artificial-Intelligence/maid/releases/tag/1.3.0

I tried your steps on the latest build and i cant reproduce it.

**Comment by PrivacyOsint2** [comment]
Will do so, thanks!

**Comment by PrivacyOsint2** [comment]
@danemadsen one error is now fixed, the other is not. Updated report above.

**Comment by danemadsen** [comment]
This should be fixed now too
